spring.application.name=order-service
server.port=8082

spring.datasource.url=jdbc:h2:mem:ordersdb
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver
spring.h2.console.enabled=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

inventory.base-url=http://localhost:8085/api/inventory/products
payments.base-url=http://localhost:8084/api/payments
shipments.base-url=http://localhost:8083/api/shipments

spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}

smartlogix.rabbitmq.exchange=${SMARTLOGIX_EVENTS_EXCHANGE:smartlogix.events}
smartlogix.rabbitmq.shipment-delivered.queue=${SHIPMENT_DELIVERED_QUEUE:orders.shipment-delivered.queue}
smartlogix.rabbitmq.shipment-delivered.routing-key=${SHIPMENT_DELIVERED_ROUTING_KEY:shipment.delivered}

smartlogix.circuitbreaker.failure-rate-threshold=50
smartlogix.circuitbreaker.sliding-window-size=6
smartlogix.circuitbreaker.minimum-number-of-calls=3
smartlogix.circuitbreaker.wait-duration-in-open-state-seconds=10
smartlogix.circuitbreaker.permitted-calls-in-half-open=2
